fail_on_violations: true
jscs:
  enabled: true
  config_file: .jscsrc_hound
javascript:
  enabled: false
scss:
  config_file: .scss.yml
exclude:
  - "public/app/components/zombify/**"
  - "public/app/components/errorView/**"
